package threads;

public class ResultTask extends Thread {
    public void run() {
        System.out.println("Result generated by :" + Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run();     //Normal execution.  ->Always the main thread or main method.
        t1.start();   // start() is for multitasking or multithreading.
    }               //start() internally calls run().
}                 //Thread cannot be started twice.


